<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'The Graphical Console allows administrators to configure basic settings in a user-friendly graphical environment';
$lang['graphical_console_app_name'] = 'Graphical Console';
$lang['graphical_console_browser_warning'] = 'Web Browser Security Warning';
$lang['graphical_console_browser_warning_help'] = 'When you connect with your web browser the first time, you will see a security warning displayed.  Please don\'t fret!';
$lang['graphical_console_command_line'] = 'Command Line';
$lang['graphical_console_command_line_help'] = 'For those of you who prefer the command line, you can jump right in by hitting the button at the bottom of this page.';
$lang['graphical_console_configure_network_now'] = 'Configure Network Now';
$lang['graphical_console_follow_link_to_change_settings:'] = 'Please follow the link to change your settings:';
$lang['graphical_console_ip_address:'] = 'The IP address of this system:';
$lang['graphical_console_network_console'] = 'Network Console';
$lang['graphical_console_no_ip_address_available'] = 'It looks like you do not have an IP address available for remote connections.';
$lang['graphical_console_shutting_down_graphical_console'] = 'Shutting down graphical console.';
$lang['graphical_console_step_1_description'] = 'Step 1. Configure Your Network Settings';
$lang['graphical_console_step_2_description'] = 'Step 2. Connect With Your Web Browser';
$lang['graphical_console_type_address_in_following_format:'] = 'Once your network is configured, type the address in the following format:';
$lang['graphical_console_type_following_address:'] = 'Start your web browser and type the following web address:';
$lang['graphical_console_web_based_interface_access'] = 'The web-based interface can be accessed on port 81 using the secure web protocol - HTTPS.';
$lang['graphical_console_welcome_message'] = 'Welcome!  This console is used to configure the network settings on this system.  Once you have your network up and running, you can install, configure and manage apps using a standard web browser.';
$lang['graphical_console_what_next'] = 'What Next?';
$lang['graphical_console_what_next_help'] = 'Once you have configured your network and connected to this system with your web browser, the install wizard will take you through the steps finish the installation.';
