#!/bin/sh

# Sudoers
#--------

/usr/sbin/addsudo /usr/bin/killall app-graphical-console

# VM screen resolution
#---------------------

logger -p local6.notice -t installer "app-graphical-console-core - configuration screen resolution"
cp /usr/clearos/apps/graphical_console/deploy/vm.conf /etc/X11/xorg.conf.d/vm.conf
