#!/bin/sh

# FIXME
# Quick workaround for startx / gconsole weirdness
#-------------------------------------------------

if [ -x /usr/bin/startx ]; then
    sed -i -e  '/./,$!d' /usr/bin/startx
fi

# FIXME: tconsole should use new path
if [ ! -e /usr/sbin/iptraf ]; then
    ln -sf /usr/sbin/iptraf-ng /usr/bin/iptraf
fi
