<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'Den grafiska konsolen tillåter administratörer att göra grundläggande inställningar i en lättanvänd miljö';
$lang['graphical_console_app_name'] = 'Grafisk konsol';
$lang['graphical_console_browser_warning'] = 'Säkerhetsvarning för webbläsaren';
$lang['graphical_console_browser_warning_help'] = 'När du ansluter till servern med din webbläsare för första gången så kommer du att se en säkerhetsvarning.   Bli inte rädd!';
$lang['graphical_console_command_line'] = 'Kommandotolk';
$lang['graphical_console_command_line_help'] = 'För de av er som föredrar kommandotolken så kan du hoppa rakt in i den genom att klicka på knappen nederst på denna sida.';
$lang['graphical_console_configure_network_now'] = 'Konfigurera nätverket nu';
$lang['graphical_console_follow_link_to_change_settings:'] = 'Please follow the link to change your settings:';
$lang['graphical_console_ip_address:'] = 'IP-adressen för detta system:';
$lang['graphical_console_network_console'] = 'Nätverkskonsol';
$lang['graphical_console_no_ip_address_available'] = 'Det verkar som att du inte har en IP-adress tillgänglig för fjärranslutningar.';
$lang['graphical_console_shutting_down_graphical_console'] = 'Avsluta den grafiska konsolen.';
$lang['graphical_console_step_1_description'] = 'Steg 1. Konfigurera dina nätverksinställningar';
$lang['graphical_console_step_2_description'] = 'Steg 2. Anslut med din webbläsare';
$lang['graphical_console_type_address_in_following_format:'] = 'När ditt nätverk är konfigurerat, skriv in en adress enligt följande format:';
$lang['graphical_console_type_following_address:'] = 'Starta din webbläsare och skriv in följande webbadress:';
$lang['graphical_console_web_based_interface_access'] = 'Det webbaserade gränssnittet kan anslutas till på port 81 och nyttjandet av webbprotokollet - HTTPS';
$lang['graphical_console_welcome_message'] = 'Välkommen!   Denna konsol används för att konfigurera nätverksinställningarna på detta system.   När du har konfigurerat ditt nätverk så installerar, konfigurerar och hanterar du appar genom att använda en vanlig webbläsare.';
$lang['graphical_console_what_next'] = 'Vad kommer härnäst?';
$lang['graphical_console_what_next_help'] = 'När du har konfigurerat ditt nätverket och anslutit till detta system med en webbläsare, så kommer installationshjälpen att hjälpa dig genom de sista stegen av installationen.';
