<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'Den grafiska konsolen tillåter administratörer att göra grundläggande inställningar i en lättanvänd miljö';
$lang['graphical_console_app_name'] = 'Grafisk konsol';
$lang['graphical_console_browser_warning'] = 'Säkerhetsvarning för webbläsaren';
$lang['graphical_console_browser_warning_help'] = 'När du ansluter till servern med din webbläsare för första gången så kommer du att se en säkerhetsvarning.   Bli inte rädd!';
$lang['graphical_console_command_line'] = 'Kommandotolk';
$lang['graphical_console_command_line_help'] = 'För de av er som föredrar kommandotolken så kan du hoppa rakt in i den genom att klicka på knappen nederst på denna sida.';
$lang['graphical_console_configure_network_now'] = 'Configure Network Now';
$lang['graphical_console_follow_link_to_change_settings:'] = 'Pleasee follow the link to change your settings:';
$lang['graphical_console_ip_address:'] = 'The IP address of this system:';
$lang['graphical_console_network_console'] = 'Nätverkskonsol';
$lang['graphical_console_no_ip_address_available'] = 'It looks like you do not have an IP address available for remote connections.';
$lang['graphical_console_shutting_down_graphical_console'] = 'Avsluta den grafiska konsolen.';
$lang['graphical_console_step_1_description'] = 'Step 1. Configure Your Network Settings';
$lang['graphical_console_step_2_description'] = 'Step 2. Connect With Your Web Browser';
$lang['graphical_console_type_address_in_following_format:'] = 'Once your network is configured, type the address in the following format:';
$lang['graphical_console_type_following_address:'] = 'Start your web browser and type the following web address:';
$lang['graphical_console_web_based_interface_access'] = 'The web-based interface can be accessed on port 81 using the secure web protocol - HTTPS.';
$lang['graphical_console_welcome_message'] = 'Welcome!  This console is used to configure the network settings on this system.  Once you have your network up and running, you can install, configure and manage apps using a standard web browser.';
$lang['graphical_console_what_next'] = 'Vad kommer härnäst?';
$lang['graphical_console_what_next_help'] = 'När du har konfigurerat ditt nätverket och anslutit till detta system med en webbläsare, så kommer installationshjälpen att hjälpa dig genom de sista stegen av installationen.';
