<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'Graficzna konsola pozwala administratorom na konfigurację podstawowych ustawień w przyjaznym dla użytkownika środowisku';
$lang['graphical_console_app_name'] = 'Graficzna konsola';
$lang['graphical_console_browser_warning'] = 'Ostrzeżenie bezpieczeństwa przeglądarki internetowej';
$lang['graphical_console_browser_warning_help'] = 'Kiedy podłączasz się przez przeglądarkę internetową, zobaczysz ostrzeżenie bezpieczeństwa.  Prosimy się nie obawiać!';
$lang['graphical_console_command_line'] = 'Wiersz poleceń';
$lang['graphical_console_command_line_help'] = 'Dla tych, którzy wolą wiersz poleceń znajduje się specjalny przycisk na dole tej strony.';
$lang['graphical_console_configure_network_now'] = 'Configure Network Now';
$lang['graphical_console_follow_link_to_change_settings:'] = 'Pleasee follow the link to change your settings:';
$lang['graphical_console_ip_address:'] = 'The IP address of this system:';
$lang['graphical_console_network_console'] = 'Sieciowa konsola';
$lang['graphical_console_no_ip_address_available'] = 'It looks like you do not have an IP address available for remote connections.';
$lang['graphical_console_shutting_down_graphical_console'] = 'Zamykam graficzną konsolę.';
$lang['graphical_console_step_1_description'] = 'Step 1. Configure Your Network Settings';
$lang['graphical_console_step_2_description'] = 'Step 2. Connect With Your Web Browser';
$lang['graphical_console_type_address_in_following_format:'] = 'Once your network is configured, type the address in the following format:';
$lang['graphical_console_type_following_address:'] = 'Start your web browser and type the following web address:';
$lang['graphical_console_web_based_interface_access'] = 'The web-based interface can be accessed on port 81 using the secure web protocol - HTTPS.';
$lang['graphical_console_welcome_message'] = 'Welcome!  This console is used to configure the network settings on this system.  Once you have your network up and running, you can install, configure and manage apps using a standard web browser.';
$lang['graphical_console_what_next'] = 'Co dalej?';
$lang['graphical_console_what_next_help'] = 'Kiedy już skonfigurowałeś sieć i podłączyłeś się do systemu przez przeglądarkę internetową, przewodnik instalacji poprowadzi Ciebie przez kolejne kroki do zakończenia instalacji.';
