<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'Graficzna konsola pozwala administratorom na konfigurację podstawowych ustawień w przyjaznym dla użytkownika środowisku';
$lang['graphical_console_app_name'] = 'Graficzna konsola';
$lang['graphical_console_browser_warning'] = 'Ostrzeżenie bezpieczeństwa przeglądarki internetowej';
$lang['graphical_console_browser_warning_help'] = 'Kiedy podłączasz się przez przeglądarkę internetową, zobaczysz ostrzeżenie bezpieczeństwa.  Prosimy się nie obawiać!';
$lang['graphical_console_command_line'] = 'Wiersz poleceń';
$lang['graphical_console_command_line_help'] = 'Dla tych, którzy wolą wiersz poleceń znajduje się specjalny przycisk na dole tej strony.';
$lang['graphical_console_network_console'] = 'Sieciowa konsola';
$lang['graphical_console_shutting_down_graphical_console'] = 'Zamykam graficzną konsolę.';
$lang['graphical_console_what_next'] = 'Co dalej?';
$lang['graphical_console_what_next_help'] = 'Kiedy już skonfigurowałeś sieć i podłączyłeś się do systemu przez przeglądarkę internetową, przewodnik instalacji poprowadzi Ciebie przez kolejne kroki do zakończenia instalacji.';
