<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['graphical_console_app_description'] = 'Graficzna konsola pozwala administratorom na konfigurację podstawowych ustawień w przyjaznym dla użytkownika środowisku';
$lang['graphical_console_app_name'] = 'Graficzna konsola';
$lang['graphical_console_browser_warning'] = 'Ostrzeżenie bezpieczeństwa przeglądarki internetowej';
$lang['graphical_console_browser_warning_help'] = 'Kiedy podłączasz się przez przeglądarkę internetową, zobaczysz ostrzeżenie bezpieczeństwa.  Prosimy się nie obawiać!';
$lang['graphical_console_command_line'] = 'Wiersz poleceń';
$lang['graphical_console_command_line_help'] = 'Dla tych, którzy wolą wiersz poleceń znajduje się specjalny przycisk na dole tej strony.';
$lang['graphical_console_configure_network_now'] = 'Skonfiguruj teraz sieć';
$lang['graphical_console_follow_link_to_change_settings:'] = 'Please follow the link to change your settings:';
$lang['graphical_console_ip_address:'] = 'Adres IP tego systemu:';
$lang['graphical_console_network_console'] = 'Sieciowa konsola';
$lang['graphical_console_no_ip_address_available'] = 'Wygląda na to, że nie masz dostępnego adresu IP na potrzeby połączeń zdalnych.';
$lang['graphical_console_shutting_down_graphical_console'] = 'Zamykam graficzną konsolę.';
$lang['graphical_console_step_1_description'] = 'Krok 1. Skonfiguruj ustawienia swojej sieci';
$lang['graphical_console_step_2_description'] = 'Krok 2. Połącz się za pomocą przeglądarki internetowej';
$lang['graphical_console_type_address_in_following_format:'] = 'Kiedy Twoja sieć zostanie skonfigurowana, wpisz adres w następującym formacie:';
$lang['graphical_console_type_following_address:'] = 'Uruchom swoją przeglądarkę internetową i wpisz następujący adres:';
$lang['graphical_console_web_based_interface_access'] = 'Webowy interfejs jest osiągalny na porcie nr 81 używając bezpiecznego połączenia - HTTPS.';
$lang['graphical_console_welcome_message'] = 'Witamy!  Ta konsola używana jest do skonfigurowania ustawień sieciowych tego systemu.  Kiedy już Twoja sieć będzie prawidłowo funkcjonować, będziesz mógł instalować, konfigurować oraz zarządzać aplikacjami używając zwyczajnej przeglądarki internetowej.';
$lang['graphical_console_what_next'] = 'Co dalej?';
$lang['graphical_console_what_next_help'] = 'Kiedy już skonfigurowałeś sieć i podłączyłeś się do systemu przez przeglądarkę internetową, przewodnik instalacji poprowadzi Ciebie przez kolejne kroki do zakończenia instalacji.';
